language: go

go:
  - 1.4

before_install:
  - sudo pip install codecov
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/lint/golint
  - go get github.com/smartystreets/goconvey

before_script:
  - go vet ./...
  - golint ./... | xargs -r false

script:
  - go test -coverprofile=coverage.txt -covermode=count

after_success:
  - go install ./...
  - codecov
